name: pfe_parking_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.7.0
  geocoding: ^2.1.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  mobile_scanner: ^3.2.0
  qr_flutter: ^4.1.0
  lottie: ^2.3.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
