name: pfe_parking_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-417.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  cloud_firestore: ^4.6.0
  flutter_screenutil: ^5.7.0
  firebase_core: ^2.10.0
  go_router: ^7.0.0
  flutter_hooks: ^0.18.6
  firebase_auth: ^4.4.2
  awesome_snackbar_content: ^0.1.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

